"""add material tables

Revision ID: 94008dd93f0c
Revises: 20260131_200000_add_public_skill_tables
Create Date: 2026-02-01 19:50:59.954077

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '94008dd93f0c'
down_revision: str | Sequence[str] | None = '20260131_200000_add_public_skill_tables'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('source_meta', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novels_title'), 'novels', ['title'], unique=False)
    op.create_index(op.f('ix_novels_user_id'), 'novels', ['user_id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('original_content', sa.Text(), nullable=True),
    sa.Column('source_path', sa.String(length=1000), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_content_hash'), 'chapters', ['content_hash'], unique=False)
    op.create_index(op.f('ix_chapters_novel_id'), 'chapters', ['novel_id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('source_path', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_chapters', sa.Integer(), nullable=False),
    sa.Column('processed_chapters', sa.Integer(), nullable=False),
    sa.Column('stage_progress', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_novel_id'), 'ingestion_jobs', ['novel_id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_status'), 'ingestion_jobs', ['status'], unique=False)
    op.create_table('story_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('main_characters', sa.Text(), nullable=True),
    sa.Column('themes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_lines_novel_id'), 'story_lines', ['novel_id'], unique=False)
    op.create_table('world_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('power_system', sa.Text(), nullable=True),
    sa.Column('world_structure', sa.Text(), nullable=True),
    sa.Column('key_factions', sa.Text(), nullable=True),
    sa.Column('special_rules', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_views_novel_id'), 'world_views', ['novel_id'], unique=True)
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('archetype', sa.String(length=100), nullable=True),
    sa.Column('first_appearance_chapter_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['first_appearance_chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=False)
    op.create_index(op.f('ix_characters_novel_id'), 'characters', ['novel_id'], unique=False)
    op.create_table('golden_fingers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('first_appearance_chapter_id', sa.Integer(), nullable=True),
    sa.Column('evolution_history', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['first_appearance_chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_golden_fingers_novel_id'), 'golden_fingers', ['novel_id'], unique=False)
    op.create_table('plots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('plot_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_excerpt', sa.Text(), nullable=True),
    sa.Column('key_entities', sa.Text(), nullable=True),
    sa.Column('time_tag', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plots_chapter_id'), 'plots', ['chapter_id'], unique=False)
    op.create_table('process_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('stage_status', sa.String(length=50), nullable=False),
    sa.Column('checkpoint_data', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_checkpoints_job_id'), 'process_checkpoints', ['job_id'], unique=False)
    op.create_index(op.f('ix_process_checkpoints_novel_id'), 'process_checkpoints', ['novel_id'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_line_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('arc_structure', sa.Text(), nullable=True),
    sa.Column('themes', sa.Text(), nullable=True),
    sa.Column('character_arcs', sa.Text(), nullable=True),
    sa.Column('inconsistencies', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_line_id'], ['story_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_story_line_id'), 'stories', ['story_line_id'], unique=False)
    op.create_table('character_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('character_a_id', sa.Integer(), nullable=False),
    sa.Column('character_b_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('established_at_plot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_a_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['character_b_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['established_at_plot_id'], ['plots.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_relationships_character_a_id'), 'character_relationships', ['character_a_id'], unique=False)
    op.create_index(op.f('ix_character_relationships_character_b_id'), 'character_relationships', ['character_b_id'], unique=False)
    op.create_index(op.f('ix_character_relationships_novel_id'), 'character_relationships', ['novel_id'], unique=False)
    op.create_table('story_plot_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_plot_links_plot_id'), 'story_plot_links', ['plot_id'], unique=False)
    op.create_index(op.f('ix_story_plot_links_story_id'), 'story_plot_links', ['story_id'], unique=False)
    op.drop_index(op.f('ix_character_relations_character_a_id'), table_name='character_relations')
    op.drop_index(op.f('ix_character_relations_character_b_id'), table_name='character_relations')
    op.drop_index(op.f('ix_character_relations_project_id'), table_name='character_relations')
    op.drop_index(op.f('ix_character_relations_relation_type'), table_name='character_relations')
    op.drop_table('character_relations')

    # Drop and recreate event_timelines table with new schema (SQLite doesn't support ALTER COLUMN)
    op.drop_index(op.f('ix_event_timelines_event_type'), table_name='event_timelines')
    op.drop_index(op.f('ix_event_timelines_project_id'), table_name='event_timelines')
    op.drop_index(op.f('ix_event_timelines_timeline_position'), table_name='event_timelines')
    op.drop_table('event_timelines')

    # Recreate event_timelines with new schema
    op.create_table('event_timelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=False),
    sa.Column('rel_order', sa.Integer(), nullable=False),
    sa.Column('time_tag', sa.String(length=100), nullable=True),
    sa.Column('uncertain', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_timelines_chapter_id'), 'event_timelines', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_event_timelines_novel_id'), 'event_timelines', ['novel_id'], unique=False)
    op.create_index(op.f('ix_event_timelines_plot_id'), 'event_timelines', ['plot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop and recreate event_timelines with old schema
    op.drop_index(op.f('ix_event_timelines_plot_id'), table_name='event_timelines')
    op.drop_index(op.f('ix_event_timelines_novel_id'), table_name='event_timelines')
    op.drop_index(op.f('ix_event_timelines_chapter_id'), table_name='event_timelines')
    op.drop_table('event_timelines')

    # Recreate event_timelines with old schema
    op.create_table('event_timelines',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('event_type', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('timeline_position', sa.INTEGER(), nullable=False),
    sa.Column('in_world_time', sa.VARCHAR(), nullable=True),
    sa.Column('importance', sa.INTEGER(), nullable=False),
    sa.Column('related_characters', sa.VARCHAR(), nullable=True),
    sa.Column('related_locations', sa.VARCHAR(), nullable=True),
    sa.Column('chapter_reference', sa.VARCHAR(), nullable=True),
    sa.Column('consequences', sa.VARCHAR(), nullable=True),
    sa.Column('foreshadowing', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_timelines_event_type'), 'event_timelines', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_timelines_project_id'), 'event_timelines', ['project_id'], unique=False)
    op.create_index(op.f('ix_event_timelines_timeline_position'), 'event_timelines', ['timeline_position'], unique=False)
    op.create_table('character_relations',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('character_a_id', sa.VARCHAR(), nullable=False),
    sa.Column('character_b_id', sa.VARCHAR(), nullable=False),
    sa.Column('relation_type', sa.VARCHAR(), nullable=False),
    sa.Column('relation_label_a_to_b', sa.VARCHAR(), nullable=False),
    sa.Column('relation_label_b_to_a', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('history', sa.VARCHAR(), nullable=True),
    sa.Column('current_status', sa.VARCHAR(), nullable=False),
    sa.Column('importance', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['character_a_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['character_b_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_relations_relation_type'), 'character_relations', ['relation_type'], unique=False)
    op.create_index(op.f('ix_character_relations_project_id'), 'character_relations', ['project_id'], unique=False)
    op.create_index(op.f('ix_character_relations_character_b_id'), 'character_relations', ['character_b_id'], unique=False)
    op.create_index(op.f('ix_character_relations_character_a_id'), 'character_relations', ['character_a_id'], unique=False)
    op.drop_index(op.f('ix_story_plot_links_story_id'), table_name='story_plot_links')
    op.drop_index(op.f('ix_story_plot_links_plot_id'), table_name='story_plot_links')
    op.drop_table('story_plot_links')
    op.drop_index(op.f('ix_character_relationships_novel_id'), table_name='character_relationships')
    op.drop_index(op.f('ix_character_relationships_character_b_id'), table_name='character_relationships')
    op.drop_index(op.f('ix_character_relationships_character_a_id'), table_name='character_relationships')
    op.drop_table('character_relationships')
    op.drop_index(op.f('ix_stories_story_line_id'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_process_checkpoints_novel_id'), table_name='process_checkpoints')
    op.drop_index(op.f('ix_process_checkpoints_job_id'), table_name='process_checkpoints')
    op.drop_table('process_checkpoints')
    op.drop_index(op.f('ix_plots_chapter_id'), table_name='plots')
    op.drop_table('plots')
    op.drop_index(op.f('ix_golden_fingers_novel_id'), table_name='golden_fingers')
    op.drop_table('golden_fingers')
    op.drop_index(op.f('ix_characters_novel_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_world_views_novel_id'), table_name='world_views')
    op.drop_table('world_views')
    op.drop_index(op.f('ix_story_lines_novel_id'), table_name='story_lines')
    op.drop_table('story_lines')
    op.drop_index(op.f('ix_ingestion_jobs_status'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_novel_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_chapters_novel_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_content_hash'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_novels_user_id'), table_name='novels')
    op.drop_index(op.f('ix_novels_title'), table_name='novels')
    op.drop_table('novels')
    # ### end Alembic commands ###
