"""add system_prompt_config table

Revision ID: c4b0247ec5dd
Revises: add_soft_delete_to_file
Create Date: 2026-01-24 22:33:28.828784

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c4b0247ec5dd'
down_revision: str | Sequence[str] | None = 'add_soft_delete_to_file'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_prompt_config',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_definition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('capabilities', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('directory_structure', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_structure', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_types', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('writing_guidelines', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('include_dialogue_guidelines', sa.Boolean(), nullable=False),
    sa.Column('primary_content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_prompt_config_is_active'), 'system_prompt_config', ['is_active'], unique=False)
    op.create_index(op.f('ix_system_prompt_config_project_type'), 'system_prompt_config', ['project_type'], unique=True)
    op.alter_column('file', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('project', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft delete flag: true if project is deleted',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('project', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when project was soft-deleted',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when project was soft-deleted',
               existing_nullable=True)
    op.alter_column('project', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete flag: true if project is deleted',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('file', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_system_prompt_config_project_type'), table_name='system_prompt_config')
    op.drop_index(op.f('ix_system_prompt_config_is_active'), table_name='system_prompt_config')
    op.drop_table('system_prompt_config')
    # ### end Alembic commands ###
