"""add_deepnovel_v3_models

Revision ID: db9a8418af28
Revises: 94008dd93f0c
Create Date: 2026-02-02 23:29:59.521054

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'db9a8418af28'
down_revision: str | Sequence[str] | None = '94008dd93f0c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.String(20), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_model', sa.String(100), nullable=False),
    sa.Column('content_checksum', sa.String(64), nullable=True),
    sa.Column('status', sa.String(16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('main_character_ids', sa.Text(), nullable=True),
    sa.Column('world_view_ids', sa.Text(), nullable=True),
    sa.Column('golden_finger_ids', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outlines_title'), 'outlines', ['title'], unique=False)
    op.create_table('character_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(255), nullable=False),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('chapter_description', sa.Text(), nullable=True),
    sa.Column('importance', sa.String(50), nullable=True),
    sa.Column('first_line', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_mentions_chapter_id'), 'character_mentions', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_character_mentions_character_name'), 'character_mentions', ['character_name'], unique=False)
    op.create_index(op.f('ix_character_mentions_novel_id'), 'character_mentions', ['novel_id'], unique=False)
    op.create_table('outline_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outline_id', sa.Integer(), nullable=False),
    sa.Column('source_story_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('custom_title', sa.String(500), nullable=True),
    sa.Column('custom_description', sa.Text(), nullable=True),
    sa.Column('author_notes', sa.Text(), nullable=True),
    sa.Column('target_words', sa.Integer(), nullable=False),
    sa.Column('custom_world_view_ids', sa.Text(), nullable=True),
    sa.Column('custom_golden_finger_ids', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['outline_id'], ['outlines.id'], ),
    sa.ForeignKeyConstraint(['source_story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outline_items_outline_id'), 'outline_items', ['outline_id'], unique=False)
    op.create_index(op.f('ix_outline_items_source_story_id'), 'outline_items', ['source_story_id'], unique=False)
    op.create_table('generated_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outline_item_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('chapter_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(20), nullable=False),
    sa.Column('task_id', sa.String(255), nullable=True),
    sa.Column('generation_status', sa.String(20), nullable=False),
    sa.Column('chapter_plan', sa.Text(), nullable=True),
    sa.Column('generation_params', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['outline_item_id'], ['outline_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_contents_outline_item_id'), 'generated_contents', ['outline_item_id'], unique=True)
    op.create_index(op.f('ix_generated_contents_task_id'), 'generated_contents', ['task_id'], unique=False)
    op.create_table('outline_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outline_item_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(100), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['outline_item_id'], ['outline_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outline_characters_character_id'), 'outline_characters', ['character_id'], unique=False)
    op.create_index(op.f('ix_outline_characters_outline_item_id'), 'outline_characters', ['outline_item_id'], unique=False)
    op.create_table('chapter_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_content_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generated_content_id'], ['generated_contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_contents_generated_content_id'), 'chapter_contents', ['generated_content_id'], unique=False)
    op.add_column('ingestion_jobs', sa.Column('correlation_id', sa.String(100), nullable=True))
    op.create_index(op.f('ix_ingestion_jobs_correlation_id'), 'ingestion_jobs', ['correlation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_jobs_correlation_id'), table_name='ingestion_jobs')
    op.drop_column('ingestion_jobs', 'correlation_id')
    op.drop_index(op.f('ix_chapter_contents_generated_content_id'), table_name='chapter_contents')
    op.drop_table('chapter_contents')
    op.drop_index(op.f('ix_outline_characters_outline_item_id'), table_name='outline_characters')
    op.drop_index(op.f('ix_outline_characters_character_id'), table_name='outline_characters')
    op.drop_table('outline_characters')
    op.drop_index(op.f('ix_generated_contents_task_id'), table_name='generated_contents')
    op.drop_index(op.f('ix_generated_contents_outline_item_id'), table_name='generated_contents')
    op.drop_table('generated_contents')
    op.drop_index(op.f('ix_outline_items_source_story_id'), table_name='outline_items')
    op.drop_index(op.f('ix_outline_items_outline_id'), table_name='outline_items')
    op.drop_table('outline_items')
    op.drop_index(op.f('ix_character_mentions_novel_id'), table_name='character_mentions')
    op.drop_index(op.f('ix_character_mentions_character_name'), table_name='character_mentions')
    op.drop_index(op.f('ix_character_mentions_chapter_id'), table_name='character_mentions')
    op.drop_table('character_mentions')
    op.drop_index(op.f('ix_outlines_title'), table_name='outlines')
    op.drop_table('outlines')
    op.drop_table('material_embeddings')
    # ### end Alembic commands ###
