/**
 * Document Chunking Utility for Virtual Scrolling
 *
 * Splits large documents into manageable chunks for virtual scrolling in the editor.
 * Each chunk is approximately 500-1000 characters for optimal rendering performance.
 *
 * Architecture:
 * - Two-pass chunking: first split into logical blocks, then split large blocks
 * - Preserves document structure (paragraphs, headings, lists, code blocks)
 * - Tracks character offsets for cursor position mapping between chunks and document
 * - Supports chunk-level editing with automatic offset recalculation
 * - Lazy/progressive chunking for large documents (>30k chars)
 * - Generator-based streaming for memory-efficient processing
 *
 * Content Detection:
 * - Headings: lines starting with # (1-6 hash marks)
 * - Code blocks: fenced with ``` or 4-space indentation
 * - Lists: bullet lists (-, *, +) or numbered lists (1., 2., etc.)
 * - Blockquotes: lines starting with >
 * - Separators: horizontal rules (---, ***, ___)
 * - Paragraphs: everything else
 *
 * Usage:
 * ```ts
 * import {
 *   chunkDocument,
 *   mergeChunks,
 *   findChunkAtOffset,
 *   shouldVirtualize
 * } from '../lib/documentChunker';
 *
 * // Check if virtualization is needed
 * if (shouldVirtualize(documentContent)) {
 *   // Chunk the document
 *   const chunks = chunkDocument(documentContent);
 *
 *   // Render visible chunks for virtual scrolling
 *   const visibleChunks = getVisibleChunks(scrollTop, viewportHeight);
 *
 *   // Find chunk at cursor position
 *   const activeChunk = findChunkAtOffset(chunks, cursorOffset);
 *
 *   // Merge chunks back when saving
 *   const fullDocument = mergeChunks(chunks);
 * }
 * ```
 *
 * For large documents, use lazy chunking:
 * ```ts
 * import { chunkDocumentInitial, continueChunking } from '../lib/documentChunker';
 *
 * // Initial chunking for fast first render
 * const initial = chunkDocumentInitial(largeDocument);
 *
 * // Continue chunking on scroll or idle
 * if (!initial.isComplete) {
 *   const result = continueChunking(
 *     largeDocument,
 *     initial.chunkedUntil,
 *     initial.chunks
 *   );
 * }
 * ```
 *
 * @module lib/documentChunker
 */

/**
 * Block types that can be detected in the document.
 *
 * Used for semantic classification of chunks, which affects:
 * - Height estimation (code blocks get extra padding)
 * - Rendering behavior (different components for different types)
 * - Editing behavior (preserving structure during modifications)
 */
export type ChunkType =
  | 'paragraph'   // Regular text content
  | 'heading'     // Markdown headings (# ## ### etc.)
  | 'code'        // Fenced code blocks or indented code
  | 'list'        // Bullet or numbered lists
  | 'blockquote'  // Quoted content (>)
  | 'separator'   // Horizontal rules (--- *** ___)
  | 'empty';      // Blank lines

/**
 * Represents a single chunk of the document for virtual scrolling.
 *
 * Each chunk contains enough metadata to:
 * - Calculate its position in the virtual list (estimatedHeight)
 * - Map cursor positions between chunk-local and document-global coordinates
 * - Identify its semantic type for specialized rendering
 *
 * @example
 * ```ts
 * const chunk: DocumentChunk = {
 *   id: 'chunk-1705312800000-0',
 *   content: '# Introduction\n\nThis is the first paragraph...',
 *   startOffset: 0,
 *   endOffset: 52,
 *   type: 'heading',
 *   estimatedHeight: 72,
 *   isPartial: false,
 *   lineNumber: 1
 * };
 * ```
 */
export interface DocumentChunk {
  /** Unique identifier for the chunk, generated by generateChunkId() */
  id: string;
  /** The text content of this chunk (subset of the original document) */
  content: string;
  /** Character offset where this chunk starts in the original document (0-indexed, inclusive) */
  startOffset: number;
  /** Character offset where this chunk ends in the original document (0-indexed, exclusive) */
  endOffset: number;
  /** Semantic type of content in this chunk, detected by detectChunkType() */
  type: ChunkType;
  /** Estimated height in pixels for virtual scrolling layout calculation */
  estimatedHeight: number;
  /** Whether this chunk is part of a larger block that was split due to exceeding maxChunkSize */
  isPartial: boolean;
  /** Line number where this chunk starts in the document (1-indexed) */
  lineNumber: number;
}

/**
 * Configuration options for chunking behavior.
 *
 * Controls how documents are split into chunks, balancing:
 * - Rendering performance (fewer large chunks vs more small chunks)
 * - Edit granularity (smaller chunks = more precise updates)
 * - Height estimation accuracy (affects virtual scroll positioning)
 *
 * @example
 * ```ts
 * // For code-heavy documents with longer lines
 * const codeOptions: ChunkingOptions = {
 *   targetChunkSize: 500,
 *   maxChunkSize: 1000,
 *   charsPerLine: 60,  // Code has shorter lines
 * };
 *
 * // For prose documents with standard formatting
 * const proseOptions: ChunkingOptions = {
 *   targetChunkSize: 750,
 *   charsPerLine: 80,
 * };
 * ```
 */
export interface ChunkingOptions {
  /** Target character count per chunk (default: 750). Affects average chunk size. */
  targetChunkSize?: number;
  /** Minimum character count per chunk (default: 100). Prevents tiny chunks. */
  minChunkSize?: number;
  /** Maximum character count per chunk (default: 1500). Hard limit before splitting. */
  maxChunkSize?: number;
  /** Average line height in pixels for virtual scroll estimation (default: 24). */
  lineHeight?: number;
  /** Average characters per line for height estimation (default: 80). */
  charsPerLine?: number;
}

const DEFAULT_OPTIONS: Required<ChunkingOptions> = {
  targetChunkSize: 750,
  minChunkSize: 100,
  maxChunkSize: 1500,
  lineHeight: 24,
  charsPerLine: 80,
};

/**
 * Generate a unique chunk identifier.
 *
 * Creates unique IDs using timestamp and incrementing counter pattern.
 * IDs are used to track chunks across updates and for React key props.
 *
 * @returns Unique chunk ID string in format "chunk-{timestamp}-{counter}"
 *
 * @example
 * ```ts
 * const id1 = generateChunkId(); // "chunk-1705312800000-0"
 * const id2 = generateChunkId(); // "chunk-1705312800000-1"
 * ```
 */
let chunkIdCounter = 0;
export function generateChunkId(): string {
  return `chunk-${Date.now()}-${chunkIdCounter++}`;
}

function getStableChunkId(startOffset: number): string {
  return `chunk-${startOffset}`;
}

/**
 * Reset the chunk ID counter to zero.
 *
 * Useful for testing to ensure consistent chunk IDs across test cases.
 * Should not be called in production code as it may cause ID collisions.
 *
 * @example
 * ```ts
 * // In test setup
 * beforeEach(() => {
 *   resetChunkIdCounter();
 * });
 *
 * // Now generateChunkId() will always start from 0
 * const id = generateChunkId(); // "chunk-{timestamp}-0"
 * ```
 */
export function resetChunkIdCounter(): void {
  chunkIdCounter = 0;
}

/**
 * Detect the semantic type of content based on Markdown patterns.
 *
 * Analyzes text content to classify it into chunk types for specialized
 * rendering and height estimation. Uses pattern matching for common
 * Markdown elements.
 *
 * Detection order (first match wins):
 * 1. Empty - whitespace only
 * 2. Code - fenced blocks (```) or 4-space indentation
 * 3. Heading - lines starting with 1-6 hash marks
 * 4. List - bullet lists (-, *, +) or numbered lists (1., 2., etc.)
 * 5. Blockquote - lines starting with >
 * 6. Separator - horizontal rules (---, ***, ___)
 * 7. Paragraph - everything else (default)
 *
 * @param text - The text content to analyze
 * @returns The detected ChunkType
 *
 * @example
 * ```ts
 * detectChunkType('# Chapter One');     // 'heading'
 * detectChunkType('```javascript\n...'); // 'code'
 * detectChunkType('- First item');      // 'list'
 * detectChunkType('> Quote');           // 'blockquote'
 * detectChunkType('---');               // 'separator'
 * detectChunkType('   ');               // 'empty'
 * detectChunkType('Regular text.');     // 'paragraph'
 * ```
 */
export function detectChunkType(text: string): ChunkType {
  const trimmed = text.trim();

  if (trimmed.length === 0) {
    return 'empty';
  }

  // Code block detection (``` or 4-space indent)
  if (trimmed.startsWith('```') || /^ {4}/m.test(text)) {
    return 'code';
  }

  // Heading detection (# ## ### etc.)
  if (/^#{1,6}\s/.test(trimmed)) {
    return 'heading';
  }

  // List detection (- * + or numbered)
  if (/^[-*+]\s/.test(trimmed) || /^\d+\.\s/.test(trimmed)) {
    return 'list';
  }

  // Blockquote detection (>)
  if (/^>\s/.test(trimmed)) {
    return 'blockquote';
  }

  // Separator detection (--- *** ___)
  if (/^[-*_]{3,}$/.test(trimmed)) {
    return 'separator';
  }

  return 'paragraph';
}

/**
 * Estimate the rendered height of a chunk in pixels.
 *
 * Uses character count and chunk type to approximate visual height
 * for virtual scroll positioning. Code blocks get extra padding.
 * Accuracy affects scroll behavior but not functionality.
 *
 * Height calculation:
 * - Empty chunks: 1 line height
 * - Normal chunks: (chars / charsPerLine) * lineHeight
 * - Code blocks: +2 extra line heights for padding
 *
 * @param content - The text content of the chunk
 * @param type - The semantic type of the chunk
 * @param options - Chunking options with lineHeight and charsPerLine
 * @returns Estimated height in pixels
 *
 * @example
 * ```ts
 * const options = { lineHeight: 24, charsPerLine: 80, ... };
 *
 * // Short paragraph
 * estimateChunkHeight('Hello world', 'paragraph', options); // ~24px
 *
 * // Longer paragraph (~2 lines)
 * estimateChunkHeight('A'.repeat(100), 'paragraph', options); // ~48px
 *
 * // Code block with extra padding
 * estimateChunkHeight('const x = 1;', 'code', options); // ~72px (3 lines)
 * ```
 */
export function estimateChunkHeight(
  content: string,
  type: ChunkType,
  options: Required<ChunkingOptions>
): number {
  if (type === 'empty') {
    return options.lineHeight; // Empty lines take one line
  }

  // Calculate number of lines based on content length and chars per line
  const lineCount = Math.ceil(content.length / options.charsPerLine);

  // Add extra lines for code blocks (usually displayed with padding)
  const extraLines = type === 'code' ? 2 : 0;

  // Estimate height based on line count and line height
  return (lineCount + extraLines) * options.lineHeight;
}

/**
 * Split document content into logical blocks (paragraphs, headings, etc.).
 *
 * First pass of the chunking algorithm. Identifies semantic boundaries
 * in the document to preserve structure. Related content is kept together
 * (e.g., list items stay in the same block until a blank line appears).
 *
 * Block boundary detection:
 * - Code blocks are kept intact (from ``` to ```)
 * - Blank lines end the current block
 * - Headings always start a new block
 * - Consecutive list items stay together
 * - Consecutive blockquote lines stay together
 *
 * @param content - The full document content to split
 * @returns Array of block strings, each representing a logical unit
 *
 * @example
 * ```ts
 * const markdown = `# Chapter 1
 *
 * This is a paragraph.
 *
 * - Item 1
 * - Item 2
 *
 * \`\`\`js
 * code here
 * \`\`\``;
 *
 * const blocks = splitIntoBlocks(markdown);
 * // Returns 4 blocks: heading, paragraph, list, code block
 * ```
 */
export function splitIntoBlocks(content: string): string[] {
  // Handle empty content
  if (!content) {
    return [];
  }

  const blocks: string[] = [];
  let currentBlock: string[] = [];
  let inCodeBlock = false;
  let codeBlockDelimiter = '';

  const lines = content.split('\n');

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const nextLine = lines[i + 1] || '';

    // Track code block state
    if (line.trim().startsWith('```')) {
      if (!inCodeBlock) {
        // Starting a code block
        if (currentBlock.length > 0) {
          blocks.push(currentBlock.join('\n'));
          currentBlock = [];
        }
        inCodeBlock = true;
        codeBlockDelimiter = line.trim().slice(0, line.trim().indexOf('`') + 3);
        currentBlock.push(line);
      } else if (line.trim().startsWith(codeBlockDelimiter.slice(0, 3))) {
        // Ending a code block
        currentBlock.push(line);
        blocks.push(currentBlock.join('\n'));
        currentBlock = [];
        inCodeBlock = false;
        codeBlockDelimiter = '';
      } else {
        // Continue code block content
        currentBlock.push(line);
      }
      continue;
    }

    if (inCodeBlock) {
      currentBlock.push(line);
      continue;
    }

    // Check for blank line (block separator)
    const isBlankLine = line.trim() === '';
    const nextIsBlankLine = nextLine.trim() === '';

    // Check for list continuation
    const isListLine = /^[-*+]\s/.test(line.trim()) || /^\d+\.\s/.test(line.trim());
    const nextIsListLine = /^[-*+]\s/.test(nextLine.trim()) || /^\d+\.\s/.test(nextLine.trim());

    // Check for heading
    const isHeading = /^#{1,6}\s/.test(line.trim());

    // Check for blockquote
    const isBlockquote = /^>\s/.test(line.trim());
    const nextIsBlockquote = /^>\s/.test(nextLine.trim());

    // Determine if we should end the current block
    const shouldEndBlock =
      isBlankLine ||
      isHeading ||
      (isListLine && !nextIsListLine && !nextIsBlankLine) ||
      (isBlockquote && !nextIsBlockquote && !nextIsBlankLine) ||
      (!isListLine && nextIsListLine) ||
      (!isBlockquote && nextIsBlockquote);

    currentBlock.push(line);

    if (shouldEndBlock && currentBlock.length > 0) {
      // When joining lines with '\n', a blank line at the end loses its '\n'
      // because join only puts separators BETWEEN elements, not after the last.
      // Fix: if the block ends with a blank line, add an extra '\n' to preserve it.
      let blockContent = currentBlock.join('\n');
      if (isBlankLine) {
        // Block ends with blank line - add extra newline to preserve it
        blockContent += '\n';
      }
      blocks.push(blockContent);
      currentBlock = [];
    }
  }

  // Don't forget the last block
  if (currentBlock.length > 0) {
    blocks.push(currentBlock.join('\n'));
  }

  return blocks;
}

/**
 * Split a block that exceeds the maximum chunk size into smaller pieces.
 *
 * Second pass of chunking for blocks that are too large. Tries to find
 * natural break points in order of preference:
 * 1. Chinese sentence end (。)
 * 2. English sentence end (. )
 * 3. Paragraph break (\n\n)
 * 4. Word boundary (space)
 * 5. Force split at target size (last resort)
 *
 * The search window extends ±100 characters around the target size
 * to find the best break point.
 *
 * @param block - The block content to potentially split
 * @param maxSize - Maximum allowed chunk size (hard limit)
 * @param targetSize - Target chunk size for splitting
 * @returns Array of sub-chunks (single element if block fits)
 *
 * @example
 * ```ts
 * // Block under max size - returned as-is
 * splitLargeBlock('Short block', 1500, 750);
 * // Returns: ['Short block']
 *
 * // Long block - split at sentence boundary
 * const longText = 'First sentence here. Second sentence here. Third.';
 * splitLargeBlock(longText, 30, 20);
 * // Returns: ['First sentence here. ', 'Second sentence here. ', 'Third.']
 * ```
 */
export function splitLargeBlock(
  block: string,
  maxSize: number,
  targetSize: number
): string[] {
  if (block.length <= maxSize) {
    return [block];
  }

  // Ensure targetSize doesn't exceed maxSize
  const effectiveTargetSize = Math.min(targetSize, maxSize);
  const chunks: string[] = [];
  let remaining = block;

  while (remaining.length > 0) {
    if (remaining.length <= maxSize) {
      chunks.push(remaining);
      break;
    }

    // Try to find a good split point
    let splitPoint = effectiveTargetSize;

    // Look for sentence boundary near the target size
    const searchStart = Math.max(0, effectiveTargetSize - 100);
    const searchEnd = Math.min(remaining.length, effectiveTargetSize + 100);
    const searchText = remaining.slice(searchStart, searchEnd);

    // Priority: sentence end > paragraph break > word boundary
    const sentenceEnd = searchText.lastIndexOf('。');
    const sentenceEndEn = searchText.lastIndexOf('. ');
    const paragraphBreak = searchText.indexOf('\n\n');
    const wordBoundary = searchText.lastIndexOf(' ');

    // Choose the best split point, but ensure it doesn't exceed maxSize
    let bestSplit = -1;

    if (sentenceEnd > effectiveTargetSize / 2) {
      bestSplit = searchStart + sentenceEnd + 1;
    } else if (sentenceEndEn > effectiveTargetSize / 2) {
      bestSplit = searchStart + sentenceEndEn + 2;
    } else if (paragraphBreak > 0) {
      bestSplit = searchStart + paragraphBreak + 2;
    } else if (wordBoundary > 0) {
      bestSplit = searchStart + wordBoundary + 1;
    }

    // If no good split point found, or split point exceeds maxSize, force split at maxSize
    if (bestSplit <= 0 || bestSplit > maxSize || bestSplit >= remaining.length) {
      splitPoint = Math.min(maxSize, remaining.length);
    } else {
      splitPoint = bestSplit;
    }

    chunks.push(remaining.slice(0, splitPoint));
    remaining = remaining.slice(splitPoint);
  }

  return chunks;
}

/**
 * Chunk a document into manageable pieces for virtual scrolling.
 *
 * Main entry point for document chunking. Applies two-pass algorithm:
 * 1. Split into logical blocks (splitIntoBlocks)
 * 2. Split large blocks if needed (splitLargeBlock)
 *
 * Each chunk gets metadata for:
 * - Unique identification (id)
 * - Offset tracking (startOffset, endOffset)
 * - Semantic classification (type)
 * - Height estimation (estimatedHeight)
 * - Line tracking (lineNumber)
 *
 * @param content - The full document content to chunk
 * @param options - Chunking configuration options (optional)
 * @returns Array of DocumentChunk objects with metadata, empty array if content is empty
 *
 * @example
 * ```ts
 * const document = `# My Novel
 *
 * Chapter one content here...
 *
 * ## Section 1
 *
 * More content...`;
 *
 * const chunks = chunkDocument(document);
 * // chunks[0] = { id: 'chunk-...', content: '# My Novel\n\n', type: 'heading', ... }
 * // chunks[1] = { id: 'chunk-...', content: 'Chapter one content...', type: 'paragraph', ... }
 * ```
 *
 * @example
 * ```ts
 * // With custom options for code-heavy documents
 * const chunks = chunkDocument(codeDocument, {
 *   targetChunkSize: 500,
 *   maxChunkSize: 1000,
 *   charsPerLine: 60
 * });
 * ```
 */
export function chunkDocument(
  content: string,
  options: ChunkingOptions = {}
): DocumentChunk[] {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const chunks: DocumentChunk[] = [];

  if (!content || content.length === 0) {
    return chunks;
  }

  // Split into logical blocks first
  const blocks = splitIntoBlocks(content);

  let currentOffset = 0;
  let lineNumber = 1;

  for (const block of blocks) {
    // Find the actual position of this block in the original content
    const blockStartInContent = content.indexOf(block, currentOffset);

    // Split large blocks if needed
    const subChunks = splitLargeBlock(block, opts.maxChunkSize, opts.targetChunkSize);

    for (let i = 0; i < subChunks.length; i++) {
      const subChunk = subChunks[i];
      const type = detectChunkType(subChunk);

      const chunk: DocumentChunk = {
        id: generateChunkId(),
        content: subChunk,
        startOffset: blockStartInContent + (i > 0 ? subChunks.slice(0, i).join('').length : 0),
        endOffset: blockStartInContent + subChunks.slice(0, i + 1).join('').length,
        type,
        estimatedHeight: estimateChunkHeight(subChunk, type, opts),
        isPartial: subChunks.length > 1,
        lineNumber,
      };

      chunks.push(chunk);

      // Update line number for next chunk
      lineNumber += subChunk.split('\n').length - 1;
    }

    // Update current offset for next block search
    currentOffset = blockStartInContent + block.length;
    lineNumber += block.split('\n').length - 1;
  }

  // Recalculate offsets to ensure accuracy
  let offset = 0;
  for (const chunk of chunks) {
    chunk.startOffset = offset;
    chunk.endOffset = offset + chunk.content.length;
    chunk.id = getStableChunkId(chunk.startOffset);
    offset = chunk.endOffset;

    // Account for newlines between chunks (they belong to the chunk)
    const nextChunkIndex = chunks.indexOf(chunk) + 1;
    if (nextChunkIndex < chunks.length) {
      // The newline(s) between this chunk and the next
      // are already included in the block, so no adjustment needed
    }
  }

  return chunks;
}

/**
 * Merge chunks back into a complete document string.
 *
 * Reconstructs the original document from chunk array. Chunks are
 * sorted by startOffset to ensure correct order regardless of input order.
 *
 * Use this when:
 * - Saving the document
 * - Exporting content
 * - Getting full text for search/analysis
 *
 * @param chunks - Array of document chunks (order doesn't matter)
 * @returns The complete document content, empty string if chunks is empty
 *
 * @example
 * ```ts
 * const chunks = chunkDocument(originalContent);
 * // ... user edits chunks ...
 * const savedContent = mergeChunks(chunks);
 * // savedContent can now be sent to backend
 * ```
 *
 * @example
 * ```ts
 * // Works with any chunk order
 * const reversed = [...chunks].reverse();
 * mergeChunks(reversed) === mergeChunks(chunks); // true
 * ```
 */
export function mergeChunks(chunks: DocumentChunk[]): string {
  if (chunks.length === 0) {
    return '';
  }

  // Sort chunks by start offset to ensure correct order
  const sortedChunks = [...chunks].sort((a, b) => a.startOffset - b.startOffset);

  return sortedChunks.map(chunk => chunk.content).join('');
}

/**
 * Update a specific chunk's content and recalculate offsets for all subsequent chunks.
 *
 * When a chunk's content changes, all following chunks need their offsets
 * adjusted. This function handles that recalculation automatically.
 *
 * The function also updates:
 * - endOffset of the modified chunk
 * - startOffset and endOffset of all subsequent chunks
 * - type classification (if content type changed)
 * - estimatedHeight (if content length changed)
 *
 * @param chunks - Current array of chunks (not modified in place)
 * @param chunkId - ID of the chunk to update
 * @param newContent - New content for the chunk
 * @param options - Chunking options for height estimation (optional)
 * @returns New array of chunks with updated content and offsets
 *
 * @example
 * ```ts
 * const chunks = chunkDocument('Hello world');
 * const firstChunk = chunks[0];
 *
 * // User edits the first chunk
 * const updated = updateChunkContent(
 *   chunks,
 *   firstChunk.id,
 *   'Hello universe and beyond!'
 * );
 *
 * // updated[0].content === 'Hello universe and beyond!'
 * // All subsequent chunks have adjusted offsets
 * ```
 *
 * @example
 * ```ts
 * // If chunkId not found, returns original array unchanged
 * const result = updateChunkContent(chunks, 'invalid-id', 'new');
 * result === chunks; // true (same reference)
 * ```
 */
export function updateChunkContent(
  chunks: DocumentChunk[],
  chunkId: string,
  newContent: string,
  options: ChunkingOptions = {}
): DocumentChunk[] {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const chunkIndex = chunks.findIndex(c => c.id === chunkId);

  if (chunkIndex === -1) {
    return chunks;
  }

  const chunk = chunks[chunkIndex];
  const contentDiff = newContent.length - chunk.content.length;

  // Create updated chunk
  const updatedChunk: DocumentChunk = {
    ...chunk,
    content: newContent,
    endOffset: chunk.startOffset + newContent.length,
    type: detectChunkType(newContent),
    estimatedHeight: estimateChunkHeight(newContent, detectChunkType(newContent), opts),
  };

  // Update all subsequent chunks' offsets
  const updatedChunks = chunks.map((c, index) => {
    if (index === chunkIndex) {
      return updatedChunk;
    }
    if (index > chunkIndex) {
      return {
        ...c,
        startOffset: c.startOffset + contentDiff,
        endOffset: c.endOffset + contentDiff,
      };
    }
    return c;
  });

  return updatedChunks;
}

/**
 * Find the chunk containing a specific character offset in the document.
 *
 * Used to locate which chunk the cursor is in when mapping from
 * document position to chunk position for virtual scrolling.
 *
 * @param chunks - Array of document chunks to search
 * @param offset - Global character offset to find (0-indexed)
 * @returns The chunk containing the offset, or undefined if offset is out of range
 *
 * @example
 * ```ts
 * const chunks = chunkDocument('Hello\n\nWorld');
 * // chunks[0]: startOffset=0, endOffset=7 ('Hello\n\n')
 * // chunks[1]: startOffset=7, endOffset=12 ('World')
 *
 * findChunkAtOffset(chunks, 2);  // chunks[0] (inside 'Hello')
 * findChunkAtOffset(chunks, 6);  // chunks[0] (at newline)
 * findChunkAtOffset(chunks, 8);  // chunks[1] (inside 'World')
 * findChunkAtOffset(chunks, 20); // undefined (out of range)
 * ```
 */
export function findChunkAtOffset(
  chunks: DocumentChunk[],
  offset: number
): DocumentChunk | undefined {
  return chunks.find(chunk =>
    offset >= chunk.startOffset && offset < chunk.endOffset
  );
}

/**
 * Find the chunk containing a specific line number in the document.
 *
 * Useful for scroll-to-line functionality and error highlighting
 * when line numbers are known (e.g., from linter errors).
 *
 * @param chunks - Array of document chunks to search
 * @param lineNumber - Line number to find (1-indexed)
 * @returns The chunk containing the line, or undefined if line is out of range
 *
 * @example
 * ```ts
 * const chunks = chunkDocument('Line 1\nLine 2\n\nLine 4');
 *
 * findChunkAtLine(chunks, 1); // First chunk
 * findChunkAtLine(chunks, 3); // Chunk containing empty line
 * findChunkAtLine(chunks, 100); // undefined
 * ```
 */
export function findChunkAtLine(
  chunks: DocumentChunk[],
  lineNumber: number
): DocumentChunk | undefined {
  let currentLine = 1;

  for (const chunk of chunks) {
    const chunkLines = chunk.content.split('\n').length;
    const chunkEndLine = currentLine + chunkLines - 1;

    if (lineNumber >= currentLine && lineNumber <= chunkEndLine) {
      return chunk;
    }

    currentLine = chunkEndLine + 1;
  }

  return undefined;
}

/**
 * Convert a global document offset to a chunk-local offset.
 *
 * Maps cursor positions from document space to chunk space.
 * Useful when you need to position a cursor within a specific
 * chunk's editor component.
 *
 * @param chunk - The chunk to convert within
 * @param globalOffset - Global character offset in the document
 * @returns Local offset within the chunk (0 to chunk.content.length - 1)
 *
 * @example
 * ```ts
 * const chunk = { startOffset: 100, endOffset: 150, ... };
 *
 * globalToLocalOffset(chunk, 125); // 25 (middle of chunk)
 * globalToLocalOffset(chunk, 100); // 0 (start of chunk)
 * globalToLocalOffset(chunk, 50);  // 0 (clamped, offset is before chunk)
 * ```
 */
export function globalToLocalOffset(chunk: DocumentChunk, globalOffset: number): number {
  return Math.max(0, globalOffset - chunk.startOffset);
}

/**
 * Convert a chunk-local offset to a global document offset.
 *
 * Maps cursor positions from chunk space to document space.
 * Useful when saving cursor position or reporting errors with
 * document-wide offsets.
 *
 * @param chunk - The chunk to convert from
 * @param localOffset - Local offset within the chunk (0-indexed)
 * @returns Global character offset in the document
 *
 * @example
 * ```ts
 * const chunk = { startOffset: 100, endOffset: 150, ... };
 *
 * localToGlobalOffset(chunk, 0);  // 100 (start maps to global start)
 * localToGlobalOffset(chunk, 25); // 125 (middle of chunk)
 * localToGlobalOffset(chunk, 50); // 150 (end of chunk)
 * ```
 */
export function localToGlobalOffset(chunk: DocumentChunk, localOffset: number): number {
  return chunk.startOffset + localOffset;
}

/**
 * Get statistics about a chunked document.
 *
 * Computes aggregate metrics useful for debugging, performance analysis,
 * and displaying document info to users.
 *
 * @param chunks - Array of document chunks to analyze
 * @returns Statistics object with:
 *   - totalChunks: Number of chunks
 *   - totalCharacters: Sum of all chunk content lengths
 *   - averageChunkSize: Mean chunk size in characters
 *   - maxChunkSize: Largest chunk size
 *   - minChunkSize: Smallest chunk size
 *   - estimatedTotalHeight: Sum of estimated heights (for scroll area)
 *   - chunksByType: Count of each chunk type
 *
 * @example
 * ```ts
 * const chunks = chunkDocument(largeDocument);
 * const stats = getChunkStats(chunks);
 *
 * console.log(`Document has ${stats.totalChunks} chunks`);
 * console.log(`Average chunk size: ${stats.averageChunkSize} chars`);
 * console.log(`Estimated scroll height: ${stats.estimatedTotalHeight}px`);
 * console.log('Chunks by type:', stats.chunksByType);
 * // { paragraph: 45, heading: 12, code: 3, list: 8, ... }
 * ```
 *
 * @example
 * ```ts
 * // Empty array returns zero stats
 * getChunkStats([]);
 * // { totalChunks: 0, totalCharacters: 0, ..., chunksByType: { paragraph: 0, ... } }
 * ```
 */
export function getChunkStats(chunks: DocumentChunk[]): {
  totalChunks: number;
  totalCharacters: number;
  averageChunkSize: number;
  maxChunkSize: number;
  minChunkSize: number;
  estimatedTotalHeight: number;
  chunksByType: Record<ChunkType, number>;
} {
  if (chunks.length === 0) {
    return {
      totalChunks: 0,
      totalCharacters: 0,
      averageChunkSize: 0,
      maxChunkSize: 0,
      minChunkSize: 0,
      estimatedTotalHeight: 0,
      chunksByType: {
        paragraph: 0,
        heading: 0,
        code: 0,
        list: 0,
        blockquote: 0,
        separator: 0,
        empty: 0,
      },
    };
  }

  const sizes = chunks.map(c => c.content.length);
  const chunksByType: Record<ChunkType, number> = {
    paragraph: 0,
    heading: 0,
    code: 0,
    list: 0,
    blockquote: 0,
    separator: 0,
    empty: 0,
  };

  for (const chunk of chunks) {
    chunksByType[chunk.type]++;
  }

  return {
    totalChunks: chunks.length,
    totalCharacters: chunks.reduce((sum, c) => sum + c.content.length, 0),
    averageChunkSize: Math.round(sizes.reduce((a, b) => a + b, 0) / sizes.length),
    maxChunkSize: Math.max(...sizes),
    minChunkSize: Math.min(...sizes),
    estimatedTotalHeight: chunks.reduce((sum, c) => sum + c.estimatedHeight, 0),
    chunksByType,
  };
}

/**
 * Determine if a document should use virtualized editing based on word count.
 *
 * Virtualization improves performance for large documents by only rendering
 * visible chunks. This function helps decide when to enable it.
 *
 * Word counting handles both:
 * - Chinese characters (each counts as one word)
 * - English words (sequences of letters count as one word)
 *
 * @param content - Document content to analyze
 * @param threshold - Word count threshold for virtualization (default: 10000)
 * @returns true if document exceeds threshold, false otherwise
 *
 * @example
 * ```ts
 * // Small document - no virtualization needed
 * shouldVirtualize('Short text'); // false
 *
 * // Large document - use virtualization
 * const largeNovel = '...'.repeat(100000);
 * shouldVirtualize(largeNovel); // true
 *
 * // Custom threshold
 * shouldVirtualize(content, 5000); // Use lower threshold
 * ```
 */
export function shouldVirtualize(content: string, threshold = 10000): boolean {
  // Count words (Chinese characters + English words)
  const chineseChars = (content.match(/[\u4e00-\u9fa5]/g) || []).length;
  const englishWords = (content.match(/[a-zA-Z]+/g) || []).length;
  const totalWords = chineseChars + englishWords;

  return totalWords > threshold;
}

/**
 * Count words in a document, handling both Chinese and English text.
 *
 * Counting methodology:
 * - Chinese characters (Unicode range U+4E00 to U+9FA5): each character = 1 word
 * - English words (sequences of A-Z, a-z): each sequence = 1 word
 * - Numbers and symbols are not counted
 *
 * This hybrid approach provides accurate counts for mixed-language content.
 *
 * @param content - Document content to count words in
 * @returns Total word count
 *
 * @example
 * ```ts
 * countWords('Hello world'); // 2
 * countWords('你好世界'); // 4
 * countWords('Hello 你好 world 世界'); // 4 (2 English + 4 Chinese)
 * countWords(''); // 0
 * ```
 */
export function countWords(content: string): number {
  const chineseChars = (content.match(/[\u4e00-\u9fa5]/g) || []).length;
  const englishWords = (content.match(/[a-zA-Z]+/g) || []).length;
  return chineseChars + englishWords;
}

// ============================================================================
// Lazy/Progressive Chunking for Performance Optimization
// ============================================================================

/**
 * Result of an initial (lazy) chunk operation for large documents.
 *
 * Contains only enough chunks for the first screenful, with metadata
 * to continue chunking the remaining content progressively.
 *
 * This enables fast initial render for documents that would take
 * too long to chunk entirely before display.
 *
 * @example
 * ```ts
 * const result = chunkDocumentInitial(largeDocument);
 *
 * if (result.isComplete) {
 *   // Document was small enough to chunk entirely
 *   renderAllChunks(result.chunks);
 * } else {
 *   // Render initial chunks, continue in background
 *   renderChunks(result.chunks);
 *   scheduleContinueChunking(result);
 * }
 * ```
 */
export interface LazyChunkResult {
  /** Initial chunks (enough for visible viewport area) */
  chunks: DocumentChunk[];
  /** Estimated total chunk count for the full document (for progress indicators) */
  estimatedTotalChunks: number;
  /** Character offset where initial chunking stopped (for continueChunking) */
  chunkedUntil: number;
  /** Total content length in characters */
  totalLength: number;
  /** Whether all content has been chunked (true for small documents) */
  isComplete: boolean;
}

/**
 * Minimum characters to include in initial chunking for visible area.
 *
 * Assumes ~750 chars per chunk, 16 chunks = ~12,000 chars,
 * which provides enough content for typical viewport heights.
 */
const MIN_INITIAL_CHARS = 12000;

/**
 * Chunk only the initial portion of a large document for fast first render.
 *
 * For documents under ~18k chars, chunks everything immediately.
 * For larger documents, finds a good break point and chunks only
 * the initial portion. Use continueChunking() for the rest.
 *
 * Break point selection:
 * 1. Seeks paragraph boundary (\n\n) near MIN_INITIAL_CHARS
 * 2. Falls back to line boundary (\n)
 * 3. Falls back to word boundary (space)
 * 4. Forces break at MIN_INITIAL_CHARS as last resort
 *
 * @param content - The full document content
 * @param options - Chunking configuration options (optional)
 * @returns LazyChunkResult with initial chunks and continuation metadata
 *
 * @example
 * ```ts
 * // Large document - only initial portion chunked
 * const result = chunkDocumentInitial(hugeNovel);
 *
 * // Render initial content immediately
 * setChunks(result.chunks);
 *
 * // Continue chunking in background
 * if (!result.isComplete) {
 *   requestIdleCallback(() => {
 *     const continued = continueChunking(
 *       hugeNovel,
 *       result.chunkedUntil,
 *       result.chunks
 *     );
 *     setChunks(continued.chunks);
 *   });
 * }
 * ```
 *
 * @example
 * ```ts
 * // Small document - everything chunked at once
 * const result = chunkDocumentInitial(shortText);
 * result.isComplete; // true
 * result.chunks.length === result.estimatedTotalChunks; // true
 * ```
 */
export function chunkDocumentInitial(
  content: string,
  options: ChunkingOptions = {}
): LazyChunkResult {
  const opts = { ...DEFAULT_OPTIONS, ...options };

  if (!content || content.length === 0) {
    return {
      chunks: [],
      estimatedTotalChunks: 0,
      chunkedUntil: 0,
      totalLength: 0,
      isComplete: true,
    };
  }

  // For small documents, just chunk everything
  if (content.length <= MIN_INITIAL_CHARS * 1.5) {
    const fullChunks = chunkDocument(content, opts);
    return {
      chunks: fullChunks,
      estimatedTotalChunks: fullChunks.length,
      chunkedUntil: content.length,
      totalLength: content.length,
      isComplete: true,
    };
  }

  // For large documents, only chunk the initial portion
  // Find a good break point near MIN_INITIAL_CHARS
  const breakPoint = findBreakPoint(content, MIN_INITIAL_CHARS);

  // Chunk only the initial portion
  const initialContent = content.slice(0, breakPoint);
  const initialChunks = chunkDocumentInternal(initialContent, opts, 0);

  // Estimate total chunks based on content length ratio
  const estimatedTotalChunks = Math.ceil(
    (content.length / breakPoint) * initialChunks.length
  );

  return {
    chunks: initialChunks,
    estimatedTotalChunks,
    chunkedUntil: breakPoint,
    totalLength: content.length,
    isComplete: false,
  };
}

/**
 * Continue chunking a large document from where the initial chunking stopped.
 *
 * Processes the next batch of content and appends new chunks to the
 * existing array. Offsets are calculated relative to the full document.
 *
 * Call this repeatedly until isComplete is true to fully chunk a large document.
 *
 * @param content - The full document content (not just remaining portion)
 * @param fromOffset - Character offset to continue from (use result.chunkedUntil)
 * @param existingChunks - Already chunked content (offsets preserved)
 * @param options - Chunking configuration options (optional)
 * @param batchSize - Characters to process in this batch (default: 20000)
 * @returns Object with:
 *   - chunks: Updated array with new chunks appended
 *   - newOffset: Offset to use for next continueChunking call
 *   - isComplete: Whether all content has been chunked
 *
 * @example
 * ```ts
 * // Start with initial chunking
 * let result = chunkDocumentInitial(largeDoc);
 * setChunks(result.chunks);
 *
 * // Continue chunking progressively
 * function chunkMore() {
 *   if (result.isComplete) return;
 *
 *   result = continueChunking(
 *     largeDoc,
 *     result.chunkedUntil,
 *     result.chunks
 *   );
 *   setChunks(result.chunks);
 *
 *   // Schedule next batch
 *   if (!result.isComplete) {
 *     requestIdleCallback(chunkMore);
 *   }
 * }
 *
 * chunkMore();
 * ```
 */
export function continueChunking(
  content: string,
  fromOffset: number,
  existingChunks: DocumentChunk[],
  options: ChunkingOptions = {},
  batchSize: number = 20000
): { chunks: DocumentChunk[]; newOffset: number; isComplete: boolean } {
  const opts = { ...DEFAULT_OPTIONS, ...options };

  if (fromOffset >= content.length) {
    return { chunks: existingChunks, newOffset: content.length, isComplete: true };
  }

  // Find next break point
  const remainingContent = content.slice(fromOffset);
  const endOffset = Math.min(remainingContent.length, batchSize);
  const breakPoint = findBreakPoint(remainingContent, endOffset);

  // Chunk this batch
  const batchContent = remainingContent.slice(0, breakPoint);
  const newChunks = chunkDocumentInternal(batchContent, opts, fromOffset);

  // Merge with existing chunks
  const allChunks = [...existingChunks, ...newChunks];

  const newOffset = fromOffset + breakPoint;
  const isComplete = newOffset >= content.length;

  return {
    chunks: allChunks,
    newOffset,
    isComplete,
  };
}

/**
 * Generator function for progressive document chunking.
 *
 * Yields incremental chunk arrays with progress information,
 * allowing for streaming/chunked rendering without callbacks.
 * Each yield contains all chunks processed so far.
 *
 * This is useful when you want:
 * - Async-style iteration without promises
 * - Cancellable chunking (just stop iterating)
 * - Progress updates during chunking
 *
 * @param content - The full document content
 * @param options - Chunking configuration options (optional)
 * @param batchSize - Characters to process per yield (default: 15000)
 * @yields Object with:
 *   - chunks: All chunks processed so far
 *   - progress: Completion ratio (0 to 1)
 *   - isComplete: Whether chunking is finished
 *
 * @example
 * ```ts
 * // Progressive chunking with generator
 * const generator = chunkDocumentGenerator(largeDoc);
 *
 * for (const result of generator) {
 *   setChunks(result.chunks);
 *   setProgress(result.progress * 100);
 *
 *   if (result.isComplete) {
 *     console.log('Chunking complete!');
 *     break;
 *   }
 * }
 * ```
 *
 * @example
 * ```ts
 * // Cancellable chunking
 * const generator = chunkDocumentGenerator(doc);
 * let cancelled = false;
 *
 * for (const result of generator) {
 *   if (cancelled) break; // Stop whenever you want
 *
 *   renderChunks(result.chunks);
 * }
 * ```
 */
export function* chunkDocumentGenerator(
  content: string,
  options: ChunkingOptions = {},
  batchSize: number = 15000
): Generator<{ chunks: DocumentChunk[]; progress: number; isComplete: boolean }> {
  const opts = { ...DEFAULT_OPTIONS, ...options };

  if (!content || content.length === 0) {
    yield { chunks: [], progress: 1, isComplete: true };
    return;
  }

  // Start with initial chunks
  const initial = chunkDocumentInitial(content, opts);
  yield {
    chunks: initial.chunks,
    progress: initial.chunkedUntil / content.length,
    isComplete: initial.isComplete,
  };

  if (initial.isComplete) {
    return;
  }

  // Continue chunking in batches
  let currentChunks = initial.chunks;
  let currentOffset = initial.chunkedUntil;

  while (!initial.isComplete && currentOffset < content.length) {
    const result = continueChunking(
      content,
      currentOffset,
      currentChunks,
      opts,
      batchSize
    );

    currentChunks = result.chunks;
    currentOffset = result.newOffset;

    yield {
      chunks: currentChunks,
      progress: currentOffset / content.length,
      isComplete: result.isComplete,
    };

    if (result.isComplete) {
      break;
    }
  }
}

/**
 * Find an optimal break point near the target position.
 *
 * Searches within a ±200 character window for natural break points
 * in order of preference:
 * 1. Paragraph boundary (\n\n) - ideal for preserving structure
 * 2. Line boundary (\n) - acceptable break point
 * 3. Word boundary (space) - minimal disruption
 * 4. Force break at target - last resort
 *
 * @param content - The full document content
 * @param targetPosition - Target character position for the break
 * @returns Character position after the break point (content length if at end)
 *
 * @example
 * ```ts
 * // Prefer paragraph break near target
 * findBreakPoint('Para 1\n\nPara 2\n\nPara 3', 10);
 * // Returns position after 'Para 1\n\n' (at 8)
 *
 * // Force break if no good boundary exists
 * findBreakPoint('abcdefghij', 5); // Returns 5
 * ```
 */
function findBreakPoint(content: string, targetPosition: number): number {
  if (targetPosition >= content.length) {
    return content.length;
  }

  // Search window around target (±200 chars)
  const searchStart = Math.max(0, targetPosition - 200);
  const searchEnd = Math.min(content.length, targetPosition + 200);
  const searchText = content.slice(searchStart, searchEnd);

  // Priority: double newline > single newline > space
  // We want to find the BEST break point, not just any

  // Look for paragraph break (double newline) - ideal
  const paragraphBreak = searchText.indexOf('\n\n');
  if (paragraphBreak !== -1) {
    const absolutePos = searchStart + paragraphBreak + 2;
    if (absolutePos > targetPosition - 100 && absolutePos < targetPosition + 200) {
      return Math.min(absolutePos, content.length);
    }
  }

  // Look for any paragraph break in the window
  let bestParagraphBreak = -1;
  let searchPos = 0;
  while ((searchPos = searchText.indexOf('\n\n', searchPos)) !== -1) {
    const absolutePos = searchStart + searchPos + 2;
    if (absolutePos <= targetPosition + 200) {
      bestParagraphBreak = absolutePos;
    }
    searchPos += 2;
  }
  if (bestParagraphBreak > targetPosition - 100) {
    return Math.min(bestParagraphBreak, content.length);
  }

  // Look for single newline
  const newlinePos = searchText.lastIndexOf('\n', targetPosition - searchStart + 100);
  if (newlinePos !== -1) {
    const absolutePos = searchStart + newlinePos + 1;
    if (absolutePos > targetPosition - 100) {
      return Math.min(absolutePos, content.length);
    }
  }

  // Fall back to word boundary (space)
  const spacePos = searchText.lastIndexOf(' ', targetPosition - searchStart + 100);
  if (spacePos !== -1) {
    const absolutePos = searchStart + spacePos + 1;
    if (absolutePos > targetPosition - 100) {
      return Math.min(absolutePos, content.length);
    }
  }

  // Last resort: force break at target
  return Math.min(targetPosition, content.length);
}

/**
 * Internal chunking function that processes content starting at a given offset.
 *
 * Similar to chunkDocument() but allows specifying the starting offset
 * for correct offset calculation in progressive chunking scenarios.
 *
 * @param content - Content to chunk (partial document content)
 * @param opts - Full chunking options (required)
 * @param startOffset - Starting offset for offset calculation
 * @returns Array of chunks with correct global offsets
 *
 * @internal Used by chunkDocumentInitial and continueChunking
 */
function chunkDocumentInternal(
  content: string,
  opts: Required<ChunkingOptions>,
  startOffset: number
): DocumentChunk[] {
  const chunks: DocumentChunk[] = [];

  if (!content || content.length === 0) {
    return chunks;
  }

  // Split into logical blocks first
  const blocks = splitIntoBlocks(content);

  let currentOffset = startOffset;
  let lineNumber = 1;

  // Calculate initial line number from start offset if not 0
  if (startOffset > 0) {
    // This is a simplification - for perfect accuracy we'd need the full document
    lineNumber = 1; // Will be corrected when merged with full chunks
  }

  for (const block of blocks) {
    // Split large blocks if needed
    const subChunks = splitLargeBlock(block, opts.maxChunkSize, opts.targetChunkSize);

    for (let i = 0; i < subChunks.length; i++) {
      const subChunk = subChunks[i];
      const type = detectChunkType(subChunk);

      const chunk: DocumentChunk = {
        id: generateChunkId(),
        content: subChunk,
        startOffset: currentOffset + (i > 0 ? subChunks.slice(0, i).join('').length : 0),
        endOffset: currentOffset + subChunks.slice(0, i + 1).join('').length,
        type,
        estimatedHeight: estimateChunkHeight(subChunk, type, opts),
        isPartial: subChunks.length > 1,
        lineNumber,
      };

      chunks.push(chunk);

      // Update line number for next chunk
      lineNumber += subChunk.split('\n').length - 1;
    }

    // Update current offset for next block
    currentOffset += block.length;
    lineNumber += block.split('\n').length - 1;
  }

  // Recalculate offsets to ensure accuracy
  let offset = startOffset;
  for (const chunk of chunks) {
    chunk.startOffset = offset;
    chunk.endOffset = offset + chunk.content.length;
    chunk.id = getStableChunkId(chunk.startOffset);
    offset = chunk.endOffset;
  }

  return chunks;
}

/**
 * Estimate the number of chunks in a document without actually chunking it.
 *
 * Fast O(1) calculation useful for:
 * - Progress bar sizing before chunking starts
 * - Deciding between full and lazy chunking
 * - Memory estimation
 *
 * Note: This is an approximation. Actual chunk count may vary due to
 * block boundaries and content structure.
 *
 * @param content - Document content to estimate
 * @param avgChunkSize - Average chunk size assumption (default: 750)
 * @returns Estimated number of chunks (rounded up)
 *
 * @example
 * ```ts
 * // Estimate for progress indicator
 * const estimated = estimateChunkCount(largeDoc);
 * setTotalChunks(estimated);
 *
 * // Compare with actual
 * const actual = chunkDocument(largeDoc).length;
 * console.log(`Estimated: ${estimated}, Actual: ${actual}`);
 * // Estimated: 134, Actual: 138 (close enough for progress bars)
 * ```
 */
export function estimateChunkCount(content: string, avgChunkSize: number = 750): number {
  if (!content || content.length === 0) {
    return 0;
  }
  return Math.ceil(content.length / avgChunkSize);
}

/**
 * Quickly determine if a document is "large" and needs lazy chunking.
 *
 * Uses character count (O(1)) instead of word count for speed.
 * Default threshold of 30,000 chars ≈ 10,000 words (Chinese) or
 * 5,000 words (English, assuming 6 chars/word average).
 *
 * @param content - Document content to check
 * @param threshold - Character threshold (default: 30000)
 * @returns true if document length exceeds threshold
 *
 * @example
 * ```ts
 * // Decide chunking strategy
 * if (isLargeDocument(content)) {
 *   // Use lazy chunking for fast initial render
 *   const result = chunkDocumentInitial(content);
 *   return result;
 * } else {
 *   // Full chunking is fast enough
 *   return chunkDocument(content);
 * }
 * ```
 *
 * @example
 * ```ts
 * // Custom threshold for specific use case
 * isLargeDocument(content, 50000); // Only lazy chunk very large docs
 * isLargeDocument(content, 10000); // Lazy chunk more aggressively
 * ```
 */
export function isLargeDocument(content: string, threshold: number = 30000): boolean {
  return content.length > threshold;
}
